### ISSUE TITLE
Watchdog caught collective operation timeout: WorkNCCL

### ISSUE THREAD

**Issue by Tao-Cute** [facebookresearch/llama-recipes#65]
When my code runs for a while, it gets bogged down in timeout after eval, which I've encountered on many 2,4 GPUs. It tends to happen after the code has run some epochs. I wonder if there might be a problem with model eval or model saving. At the same time the model save is saved on each rank, I am not sure if this is reasonable.

**Comment by DhruvaBansal00** [comment]
I am seeing the same error. Happens to me after 3 epochs finish. 

Based on what I am reading online, we need to increase the timeout.

https://github.com/facebookresearch/llama-recipes/blob/905f633dab92688b0a989f8d5cd11d86f882f534/utils/train_utils.py#L245

Changing the above line to:

`dist.init_process_group("nccl", timeout=datetime.timedelta(seconds=5400))`

should help!

**Comment by kushalj001** [comment]
If timeout doesn't work, try setting this environment variable: `export NCCL_P2P_DISABLE=1`.

**Comment by DhruvaBansal00** [comment]
Thanks for the recommendation @kushalj001 . I increased the timeout and yeah that didn't work either; I got the same error, after 1.5 hours this time. Rerunning with the environment variable set now.

**Comment by kushalj001** [comment]
Oh okay. That's supposed to happen, I think. This environment variable disables P2P communication between the processes, so the only way now the processes can communicate is by accessing the shared memory (which is considerably slower). I get the following error when I run without setting this variable: 
`RuntimeError: Forward order differs across ranks: rank 0 is all-gathering 0 parameters while rank 1 is all-gathering 1 parameters
`

**Comment by HamidShojanazeri** [comment]
@Tao-Cute can you pls provide more details on your setting/ the comment you are running?

**Comment by HamidShojanazeri** [comment]
This [PR](https://github.com/facebookresearch/llama-recipes/pull/51), fixes the rank0 issue mentioned above and some other additions including adding dist.barrier to make sure all processes are synced before and after checkpointing.

**Comment by jveronvialard** [comment]
@Tao-Cute were you able to solve it? I'm running into the same issue: a NCCL timeout error right after training for one full epoch, probably when trying to save the model. The issue happened after increasing training dataset size (fine-tuning worked fine before). I haven't tried increasing timeout yet.

**Comment by Tao-Cute** [comment]
> @Tao-Cute were you able to solve it? I'm running into the same issue: a NCCL timeout error right after training for one full epoch, probably when trying to save the model. The issue happened after increasing training dataset size (fine-tuning worked fine before). I haven't tried increasing timeout yet.

Did u upgrade your repo? I pull the latest repo and everything is ok.

**Comment by HamidShojanazeri** [comment]
seem issue been resolved.

**Comment by hassanzadeh** [comment]
Hi @HamidShojanazeri ,
Can I ask what has been changed recently? 
I'm getting the same error for the 70b checkpoint (but not for 7 and 13). In my case the issue happens when the model is loading the 7'th shard, so no training has started yet. But since my code is based on your last month commit my issue maybe the same.

Thanks

**Comment by polym** [comment]
**Upgrade PyTorch Nightlies don't work for me.** 

I met the same problem when using custom dataset. According to https://discuss.pytorch.org/t/a-question-about-model-test-in-ddp/140456/2, I guess something wrong with DistributedSampler,  so I try to set drop_last=True when init DistributedSampler. It works fine.

```diff
diff --git a/src/llama_recipes/finetuning.py b/src/llama_recipes/finetuning.py
index 79f971a..9f1f88b 100644
--- a/src/llama_recipes/finetuning.py
+++ b/src/llama_recipes/finetuning.py
@@ -187,12 +187,14 @@ def main(**kwargs):
             rank=dist.get_rank(),
             num_replicas=dist.get_world_size(),
             shuffle=True,
+            drop_last=True,
         )
         if train_config.run_validation:
             val_sampler = DistributedSampler(
                 dataset_val,
                 rank=dist.get_rank(),
                 num_replicas=dist.get_world_size(),
+                drop_last=True,
             )

     # Create DataLoaders for the training and validation dataset
```
